<a href="https://colab.research.google.com/github/Radhika003/python-mini-projects/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#Recap
arr = np.array([[1,2,3],[4,5,6]])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr1=np.random.randint(1,2,(3,1))

In [6]:
arr.shape

(2, 3)

In [7]:
arr1.shape

(3, 1)

In [8]:
result=np.dot(arr,arr1)

In [9]:
print(result)

[[ 6]
 [15]]


In [10]:
r1=np.random.randint(10,20,(3,3))
print(r1)

[[17 19 19]
 [13 12 15]
 [13 14 19]]


In [11]:
r2=np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# r1 = I
result2=np.dot(r1,r2)

In [13]:
print(result2)

[[17. 19. 19.]
 [13. 12. 15.]
 [13. 14. 19.]]


In [14]:
t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))

In [15]:
print(t1)
print(t2)

[[5 3 4]
 [3 4 4]
 [5 3 5]]
[[4 3 3]
 [4 5 5]
 [3 5 5]]


In [16]:
t3=t1+t2

In [17]:
print(t3)

[[ 9  6  7]
 [ 7  9  9]
 [ 8  8 10]]


In [18]:
#Matrix multiplication
result=np.dot(arr,arr1)

In [19]:
#statistical operations
mean=t3.mean()
mode=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [20]:
print(mean)

8.11111111111111


In [21]:
print(mode)

10


In [22]:
print(median)

8.0


In [23]:
print(std)

1.1967032904743342


In [24]:
print(var)

1.432098765432099


In [25]:
#Trigonomentry functions
# sin(x)
#cos(x)
#Tan(x)-sin(x)/cos(x)
#cosec-1/sin(x)
#sec-1/cos(x)
#cot-1/tan(x)
angles=np.array([0,15,30,45,60,75,90])
# sin(array)
result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [26]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [27]:
arr=np.array([1,2,3,4,5,6])
#reshape the array
reshapedarr=arr.reshape(3,2)
print(reshapedarr)
flattendarr=arr.flatten()
print(flattendarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [28]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])
arr3=np.vstack((arr1,arr2))
print(f"The shape of arr3 is{arr3.shape}")
#Horizantal Array
arr4=np.hstack((arr1,arr2))
print(f"The shape of arr4 is{arr4.shape}")
print(arr4)

The shape of arr3 is(2, 4)
The shape of arr4 is(8,)
[ 1  2  3  4 10 20 30 40]


In [29]:
#Filtering
arr=np.array([10,20,30,40,50,60,70,80])
farr=arr[arr>40]
print(farr)

[50 60 70 80]
