<a href="https://colab.research.google.com/github/Radhika003/python-mini-projects/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
#Numpy-Numaric python
#speed(numpy operations)>speed(list opretion)
#size(numpy operations)>size(list opretion)
#Memory optimization(Numpy)>Memory Optimisation (List operations)

In [22]:
#Install numpy-pip3 install numpy

In [23]:
import numpy as np

In [24]:
#create a numpy array
#1D array
arr1D=np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [25]:
#Create 2D array-Matrix
arr2D=np.array([
    [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [26]:
allOnes=np.ones((2,3))
print(allOnes)

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
allConstant=np.full((2,3),6)
print(allConstant)

[[6 6 6]
 [6 6 6]]


In [28]:

allZeros=np.zeros((2,3))
print(allZeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#create an identify matrix-1
identity=np.eye(4)
print(identity)

#Identity matrix-Aij=1&&Aij=0
# For all A belongs to R M*N
#Aij-

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
#Creating a random Matrices

#with 0and1
rand1=np.random.rand(3,3)
print(rand1)
#between a and b
rand2=np.random.randint(10,20,(3,3))
print(rand2)

[[0.28380531 0.20832581 0.31601321]
 [0.71127244 0.89200812 0.67524014]
 [0.05334969 0.76495363 0.6580454 ]]
[[16 16 17]
 [14 18 12]
 [19 18 10]]


In [33]:
# Array properties
arr=np.array(([1,2,3,4],[2,3,4,5]))
print(arr)
# Shape of the array
print(f'The shape of the array is {arr.shape}')
# Size of array
print(f'The size of the array is {arr.size}')
#Datatype of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]
The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [45]:
# Indexing and Slicing

# Access the elements in 1D Array

arr =np.array([1,2,3,4])
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])

# Access the elements in 2D Array
arr2 = np.array(([1,2,3],[2,3,4]))
print(arr2)
print(arr2[1,1])
print(arr2[0,:])#first row with all colums
print(arr2[:,0])#first columns with all rows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [56]:
#l1=[]
#[l1.append(_) for _ in range(10)]

l1=np.arange(10,-10,-3)
print(l1)

[10  7  4  1 -2 -5 -8]


In [63]:
#Mathematcial operations
a=np.array([1,2,3])
b=np.array([3,4,5])
print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [68]:
#Matrix multiplication
b1=np.array([[1,2,3],[2,3,4]])
b2=np.array([[5,6],[7,8],[1,3]])

#Dot product ---- product=A M×n ----B n *p
c=np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [69]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]
